CURDATE:SELECT CURRENT_DATE()
NOW: SELECT NOW
DATABASE: SELECT DATABASE()
LEFT:SELECT LEFT ("EDUARDO MANOSLARGAS",5) AS ExtractString;
LCASE: SELECT LCASE ("OLA K ASE")
EXP: SELECT EXP(4)
ISNULL
BIN
SUBSTRING
LAST_INSERT_ID
REPLACE
DATE_SUB
UCASE
GREATEST
LEAST
AVG
SELECT AVG(cost) AS AveragePrice FROM items